name: Live

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

env:
  Ray_RunTasks: LiveFansMedal
  Ray_BiliBiliCookies__1: ${{ secrets.COOKIE }}
  Ray_LiveFansMedalTaskConfig__IsSkipLevel20Medal: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    strategy:
      matrix:
        dotnet: [ "8.0.x" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build and Run
        run: cd src/Ray.BiliBiliTool.Console && dotnet run
