name: Python

on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: ["main"]
    paths: ["*.py"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Initialize project
        run: |
          git clone https://github.com/Womsxd/MihoyoBBSTools.git app --depth=1
          wget ${{ secrets.HUTAO }} -O app/config/hutao.yaml
          wget ${{ secrets.PUSH }} -O app/config/push.ini
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Build and Run
        run: python app/main_multi.py autorun
      - run: cat app/config/hutao.yaml
