name: Python

on:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches: ["main"]
    paths: ["*.py"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MYS_REPO }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Loading config
        run: |
          wget ${{ secrets.HUTAO }} -O config/hutao.yaml
          wget ${{ secrets.GANYU }} -O config/ganyu.yaml
          wget ${{ secrets.PUSHER }} -O config/push.ini
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and Run
        run: python main_multi.py autorun
      - run: cat config/hutao.yaml && cat config/ganyu.yaml
