name: Sign

on:
  schedule:
    - cron: "30 0 * * *"
  push:
    branches: ["main"]
    paths: ["*.py"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.SIGN_REPO }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install uvicorn fastapi httpx loguru diskcache apscheduler SQLAlchemy python-dateutil
      - name: Build and Run
        run: python sign.py --pt_pin ${{ vars.PT_PIN }} --pt_key ${{ vars.PT_KEY }}
